#!/bin/sh

APP=/usr/bin/main

case "$1" in
    start)
        echo "Starting main..."
        $APP &
        ;;
    stop)
        echo "Stopping main..."
        killall main
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0